name: '${project.name}'
version: '${project.version}'
description: '${project.description}'
main: io.mcvalorant.MCValorant
api-version: 1.20
authors: [ NYC_1809, Hakuyamu ]

commands:
  team:
    description: Command to change / set teams
    permission: valorant.command.team
  gamestate:
    description: Set / get active gamestate
    permission: valorant.command.gamestate
  debugcommand:
    description: spawn particles at player hitboxes
    permission: valorant.command.debugcommand
  buy:
    description: Open the loadout menu
    permission: valorant.player.ingame
  money:
    description: Modify the money / credits from player
    permission: valorant.command.money