name: '${project.name}'
version: '${project.version}'
description: '${project.description}'
main: io.mcvalorant.MCValorant
api-version: 1.18
authors: [ NYC_1809, Hakuyamu ]

commands:
  slime:
    description: Creates an entity to find head hitboxes
    permission: valorant.command.slime
  team:
    description: Command to change / set teams
    permission: valorant.command.team
  gamestate:
    description: Set / get active gamestate
    permission: valorant.command.gamestate